### ISSUE TITLE
frontend の generate を GitHub Actions に追加する

### ISSUE THREAD

**Issue by takano32** [spendingjp/openspending-backend#145]
`yarn generate` できない状態になっていることがある(気がする)。

- https://github.com/nuxt/nuxt.js/blob/dev/.github/workflows/nightly.yml
- https://github.com/nuxt/nuxt.js/blob/dev/.github/workflows/test.yml

**Comment by takano32** [comment]
`docker-compose` でイメージをビルドしているときにも発生したので環境の問題ではないらしい。

```
#10 146.9 Entrypoint app = 93b8b04.js a709b55.js da98bd5.js e55a88d.js
#10 146.9
#10 146.9 ERROR in pages/budgets/_slug/view.vue:58:7
#10 146.9 TS2345: Argument of type '{ wdmmgTree: null; cofogClassifications: never[]; }' is not assignable to parameter of type 'State'.
#10 146.9   Object literal may only specify known properties, and 'cofogClassifications' does not exist in type 'State'.
#10 146.9     56 |     const state = reactive<State>({
#10 146.9     57 |       wdmmgTree: null,
#10 146.9   > 58 |       cofogClassifications: [],
#10 146.9        |       ^^^^^^^^^^^^^^^^^^^^^^^^
#10 146.9     59 |     })
#10 146.9     60 |     const route = useRoute()
#10 146.9     61 |     useAsync(async () => {
#10 146.9
#10 146.9 ERROR in pages/budgets/_slug/view.vue:70:13
#10 146.9 TS2339: Property 'cofogClassifications' does not exist on type '{ wdmmgTree: { id: string; name: string; subtitle: string; slug: string; year: number; createdAt: string; updatedAt: string; government: { id: string; name: string; slug: string; latitude: number | null; longitude: number | null; createdAt: string; updatedAt: string; }; budgets: { ...; }[]; } | null; }'.
#10 146.9     68 |     })
#10 146.9     69 |     useAsync(async () => {
#10 146.9   > 70 |       state.cofogClassifications = (
#10 146.9        |             ^^^^^^^^^^^^^^^^^^^^
#10 146.9     71 |         await $axios.get<ClassifiactionSystemResponse>(
#10 146.9     72 |           `/api/v1/classification-systems/cofog/`
#10 146.9     73 |         )
#10 146.9
#10 146.9  FATAL  Nuxt build error
#10 146.9
#10 146.9   at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
#10 146.9   at runMicrotasks (<anonymous>)
#10 146.9   at processTicksAndRejections (node:internal/process/task_queues:96:5)
#10 146.9   at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
#10 146.9   at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
#10 146.9   at async ensureBuild (node_modules/@nuxt/cli/dist/cli-generate.js:145:3)
#10 146.9   at async Object.run (node_modules/@nuxt/cli/dist/cli-generate.js:283:7)
#10 146.9   at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)
#10 146.9
#10 147.0
#10 147.0    ╭─────────────────────────────╮
#10 147.0    │                             │
#10 147.0    │   ✖ Nuxt Fatal Error        │
#10 147.0    │                             │
#10 147.0    │   Error: Nuxt build error   │
#10 147.0    │                             │
#10 147.0    ╰─────────────────────────────╯
#10 147.0
#10 147.2 error Command failed with exit code 1.
#10 147.2 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by takano32** [comment]
関連 #150
