### ISSUE TITLE
cofogClassifications の周辺でエラーが発生して生成に失敗する

### ISSUE THREAD

**Issue by takano32** [spendingjp/openspending-backend#150]
yarn generate すると下記のエラーで失敗する。

```
ERROR in pages/budgets/_slug/view.vue:58:7
TS2345: Argument of type '{ wdmmgTree: null; cofogClassifications: never[]; }' is not assignable to parameter of type 'State'.
  Object literal may only specify known properties, and 'cofogClassifications' does not exist in type 'State'.
    56 |     const state = reactive<State>({
    57 |       wdmmgTree: null,
  > 58 |       cofogClassifications: [],
       |       ^^^^^^^^^^^^^^^^^^^^^^^^
    59 |     })
    60 |     const route = useRoute()
    61 |     useAsync(async () => {

ERROR in pages/budgets/_slug/view.vue:70:13
TS2339: Property 'cofogClassifications' does not exist on type '{ wdmmgTree: { id: string; name: string; subtitle: string; slug: string; year: number; createdAt: string; updatedAt: string; government: { id: string; name: string; slug: string; latitude: number | null; longitude: number | null; createdAt: string; updatedAt: string; }; budgets: { ...; }[]; } | null; }'.
    68 |     })
    69 |     useAsync(async () => {
  > 70 |       state.cofogClassifications = (
       |             ^^^^^^^^^^^^^^^^^^^^
    71 |         await $axios.get<ClassifiactionSystemResponse>(
    72 |           `/api/v1/classification-systems/cofog/`
    73 |         )

 FATAL  Nuxt build error                                                                                                  19:13:42

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async ensureBuild (node_modules/@nuxt/cli/dist/cli-generate.js:145:3)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-generate.js:283:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

```

**Comment by takano32** [comment]
関連 #150
